image: node:18

pipelines:
  default:
    - step:
        name: Build and Deploy
        caches:
          - node
        script:
          - echo "Starting deployment process..."
          - apt-get update && apt-get install -y ssh
          - echo "Connecting to the server and running the deployment script..."
          - ssh -o StrictHostKeyChecking=no maheshwari@162.240.227.210 'bash smartmaheshwari_deploy.sh'
          # - ssh -o StrictHostKeyChecking=no maheshwari@162.240.227.210 -| cd complaint_backend/ | ls | git pull origin main | screen -S -X complaint_backend_api quit | screen -S complaint_backend_api | npm install | npm run dev
